ruby:
  config_file: .ruby-style.yml
scss:
  config_file: .scss-lint.yml
  exclude: 
    - "app/assets/stylesheets/mixins.scss"
    - "app/assets/stylesheets/media_queries.scss"
    - "app/assets/stylesheets/plugins/*"
